name: Lambda Layers Management
on:
  push:
    branches:
      - main
    paths:
      - layers/**

jobs:
  check_layer_state:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: dumy
        run: |
          echo "Statrtiv"
          echo "${{ toJSON(github.event) }}"
          echo "________________________________\n ________ \n _______________"
          echo "${{toJSON(github)}}"
