name: Lambda Layers Management
on:
  push:
    branches:
      - main
    paths:
      - layers/**

jobs:
  check_layer_state:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: dumy
        run: |
          echo ${github.event.description}
          echo $github.event.description
          echo ${{github.event.description}}
          echo $github.event.action
          echo ${{ github.event }}
